-- ============================================================================
-- Migration: Partner Leads Module
-- Description: Creates tables and policies for "My Leads" module for BP/BA
-- Version: 009
-- Created: 2025-11-02
-- ============================================================================

-- ============================================================================
-- 1. PARTNER_LEADS TABLE
-- ============================================================================
-- Stores lead information generated by Business Partners and Business Associates
CREATE TABLE IF NOT EXISTS public.partner_leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Referrer information (who generated this lead)
  partner_id UUID NOT NULL REFERENCES public.partners(id) ON DELETE CASCADE,
  partner_type VARCHAR(50) NOT NULL, -- 'BUSINESS_PARTNER' or 'BUSINESS_ASSOCIATE'

  -- Lead identification
  lead_id VARCHAR(50) UNIQUE NOT NULL, -- e.g., 'L-2025-0001'

  -- Customer information
  customer_name VARCHAR(255),
  customer_mobile VARCHAR(15) NOT NULL,
  customer_email VARCHAR(255),
  customer_city VARCHAR(100),

  -- Loan details
  loan_type VARCHAR(100), -- 'Home Loan', 'Personal Loan', 'Business Loan', etc.
  required_loan_amount DECIMAL(15,2),

  -- Form submission tracking
  form_status VARCHAR(50) DEFAULT 'PENDING', -- PENDING, OPENED, FILLED, SUBMITTED
  form_completion_percentage INTEGER DEFAULT 0 CHECK (form_completion_percentage >= 0 AND form_completion_percentage <= 100),
  form_submitted_at TIMESTAMPTZ,

  -- Link tracking
  short_link VARCHAR(255), -- Generated short URL
  short_code VARCHAR(20) UNIQUE, -- e.g., 'xyz123'
  trace_token TEXT NOT NULL, -- Encrypted referral token for traceability

  -- WhatsApp tracking
  shared_via_whatsapp BOOLEAN DEFAULT FALSE,
  whatsapp_sent_count INTEGER DEFAULT 0,
  last_whatsapp_sent_at TIMESTAMPTZ,

  -- Lead status
  lead_status VARCHAR(50) DEFAULT 'NEW', -- NEW, CONTACTED, QUALIFIED, CONVERTED, DROPPED
  lead_priority VARCHAR(20) DEFAULT 'MEDIUM', -- LOW, MEDIUM, HIGH, URGENT

  -- Conversion tracking
  converted BOOLEAN DEFAULT FALSE,
  converted_to_customer_id UUID REFERENCES public.customers(id),
  converted_to_application_id UUID,
  converted_at TIMESTAMPTZ,

  -- Metadata
  collected_data JSONB DEFAULT '{}', -- Stores form submission data
  remarks TEXT,
  tags TEXT[],

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT partner_leads_mobile_check CHECK (customer_mobile ~ '^\+?[0-9]{10,15}$')
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_partner_leads_partner ON public.partner_leads(partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_leads_mobile ON public.partner_leads(customer_mobile);
CREATE INDEX IF NOT EXISTS idx_partner_leads_status ON public.partner_leads(lead_status);
CREATE INDEX IF NOT EXISTS idx_partner_leads_form_status ON public.partner_leads(form_status);
CREATE INDEX IF NOT EXISTS idx_partner_leads_short_code ON public.partner_leads(short_code);
CREATE INDEX IF NOT EXISTS idx_partner_leads_created ON public.partner_leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_partner_leads_trace_token ON public.partner_leads(trace_token);

-- Updated at trigger
CREATE OR REPLACE FUNCTION update_partner_leads_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS partner_leads_updated_at_trigger ON public.partner_leads;
CREATE TRIGGER partner_leads_updated_at_trigger
  BEFORE UPDATE ON public.partner_leads
  FOR EACH ROW
  EXECUTE FUNCTION update_partner_leads_updated_at();

-- ============================================================================
-- 2. LEAD_REFERRAL_TRACKING TABLE
-- ============================================================================
-- Tracks the complete referral chain for regulatory compliance
CREATE TABLE IF NOT EXISTS public.lead_referral_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Lead reference
  lead_id UUID NOT NULL REFERENCES public.partner_leads(id) ON DELETE CASCADE,

  -- Referral hierarchy
  shared_by_user_id UUID NOT NULL REFERENCES public.users(id),
  shared_by_role VARCHAR(50) NOT NULL, -- 'BUSINESS_PARTNER', 'BUSINESS_ASSOCIATE'
  shared_by_partner_id UUID NOT NULL REFERENCES public.partners(id),
  shared_by_partner_code VARCHAR(20), -- e.g., 'BP001', 'BA002'

  -- If BA, track their parent BP
  parent_bp_id UUID REFERENCES public.partners(id),
  parent_bp_code VARCHAR(20),

  -- Recipient information
  shared_to_mobile VARCHAR(15) NOT NULL,
  shared_to_name VARCHAR(255),

  -- Link tracking
  short_link VARCHAR(255) NOT NULL,
  short_code VARCHAR(20) NOT NULL,
  trace_token TEXT NOT NULL, -- Encrypted token: role_userID_partnerID_timestamp_random

  -- Activity tracking
  link_opened BOOLEAN DEFAULT FALSE,
  link_opened_at TIMESTAMPTZ,
  link_opened_count INTEGER DEFAULT 0,
  form_submitted BOOLEAN DEFAULT FALSE,
  form_submitted_at TIMESTAMPTZ,

  -- Metadata
  ip_addresses TEXT[], -- Track all IPs that accessed the link
  user_agents TEXT[], -- Track devices/browsers

  -- Timestamps
  generated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT lead_referral_tracking_mobile_check CHECK (shared_to_mobile ~ '^\+?[0-9]{10,15}$')
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_lead_referral_lead ON public.lead_referral_tracking(lead_id);
CREATE INDEX IF NOT EXISTS idx_lead_referral_user ON public.lead_referral_tracking(shared_by_user_id);
CREATE INDEX IF NOT EXISTS idx_lead_referral_partner ON public.lead_referral_tracking(shared_by_partner_id);
CREATE INDEX IF NOT EXISTS idx_lead_referral_token ON public.lead_referral_tracking(trace_token);
CREATE INDEX IF NOT EXISTS idx_lead_referral_short_code ON public.lead_referral_tracking(short_code);
CREATE INDEX IF NOT EXISTS idx_lead_referral_mobile ON public.lead_referral_tracking(shared_to_mobile);

-- ============================================================================
-- 3. SHORT_LINKS TABLE
-- ============================================================================
-- Stores shortened URLs for easy sharing
CREATE TABLE IF NOT EXISTS public.short_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Short code
  short_code VARCHAR(20) UNIQUE NOT NULL, -- e.g., 'xyz123'

  -- Original URL
  original_url TEXT NOT NULL,

  -- Link metadata
  created_by_user_id UUID REFERENCES public.users(id),
  created_for_entity_type VARCHAR(50), -- 'LEAD', 'CUSTOMER', 'APPLICATION'
  created_for_entity_id UUID,

  -- Related records
  lead_id UUID REFERENCES public.partner_leads(id) ON DELETE CASCADE,

  -- Analytics
  click_count INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  last_accessed_at TIMESTAMPTZ,

  -- Expiration
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Constraints
  CONSTRAINT short_links_code_format CHECK (short_code ~ '^[a-zA-Z0-9]{6,20}$')
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_short_links_code ON public.short_links(short_code);
CREATE INDEX IF NOT EXISTS idx_short_links_lead ON public.short_links(lead_id);
CREATE INDEX IF NOT EXISTS idx_short_links_creator ON public.short_links(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_short_links_active ON public.short_links(is_active, expires_at);

-- ============================================================================
-- 4. LEAD_ID SEQUENCE
-- ============================================================================
-- Create sequence for generating lead IDs
CREATE SEQUENCE IF NOT EXISTS public.partner_leads_sequence
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 1;

-- Function to generate lead ID
CREATE OR REPLACE FUNCTION generate_lead_id()
RETURNS VARCHAR(50) AS $$
DECLARE
  next_id INTEGER;
  year_part VARCHAR(4);
  lead_number VARCHAR(10);
BEGIN
  SELECT nextval('public.partner_leads_sequence') INTO next_id;
  SELECT EXTRACT(YEAR FROM CURRENT_DATE)::VARCHAR INTO year_part;
  lead_number := LPAD(next_id::TEXT, 6, '0');
  RETURN 'L-' || year_part || '-' || lead_number;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 5. SHORT CODE GENERATOR
-- ============================================================================
-- Function to generate random short codes
CREATE OR REPLACE FUNCTION generate_short_code(length INTEGER DEFAULT 8)
RETURNS VARCHAR(20) AS $$
DECLARE
  chars VARCHAR(62) := 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  result VARCHAR(20) := '';
  i INTEGER;
BEGIN
  FOR i IN 1..length LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 6. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS
ALTER TABLE public.partner_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_referral_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.short_links ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PARTNER_LEADS RLS POLICIES
-- ============================================================================

-- Partners can view their own leads
DROP POLICY IF EXISTS "Partners can view own leads" ON public.partner_leads;
CREATE POLICY "Partners can view own leads"
  ON public.partner_leads
  FOR SELECT
  USING (
    partner_id IN (
      SELECT id FROM public.partners WHERE user_id = auth.uid()
    )
  );

-- Partners can create leads for themselves
DROP POLICY IF EXISTS "Partners can create leads" ON public.partner_leads;
CREATE POLICY "Partners can create leads"
  ON public.partner_leads
  FOR INSERT
  WITH CHECK (
    partner_id IN (
      SELECT id FROM public.partners WHERE user_id = auth.uid()
    )
  );

-- Partners can update their own leads
DROP POLICY IF EXISTS "Partners can update own leads" ON public.partner_leads;
CREATE POLICY "Partners can update own leads"
  ON public.partner_leads
  FOR UPDATE
  USING (
    partner_id IN (
      SELECT id FROM public.partners WHERE user_id = auth.uid()
    )
  );

-- Partners can delete their own leads
DROP POLICY IF EXISTS "Partners can delete own leads" ON public.partner_leads;
CREATE POLICY "Partners can delete own leads"
  ON public.partner_leads
  FOR DELETE
  USING (
    partner_id IN (
      SELECT id FROM public.partners WHERE user_id = auth.uid()
    )
  );

-- Super Admins can view all leads
DROP POLICY IF EXISTS "Super admins can view all leads" ON public.partner_leads;
CREATE POLICY "Super admins can view all leads"
  ON public.partner_leads
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid()
      AND role = 'SUPER_ADMIN'
    )
  );

-- ============================================================================
-- LEAD_REFERRAL_TRACKING RLS POLICIES
-- ============================================================================

-- Partners can view their own referral tracking
DROP POLICY IF EXISTS "Partners can view own referral tracking" ON public.lead_referral_tracking;
CREATE POLICY "Partners can view own referral tracking"
  ON public.lead_referral_tracking
  FOR SELECT
  USING (
    shared_by_user_id = auth.uid()
  );

-- Partners can create referral tracking records
DROP POLICY IF EXISTS "Partners can create referral tracking" ON public.lead_referral_tracking;
CREATE POLICY "Partners can create referral tracking"
  ON public.lead_referral_tracking
  FOR INSERT
  WITH CHECK (
    shared_by_user_id = auth.uid()
  );

-- System can update referral tracking (for link opens/submissions)
DROP POLICY IF EXISTS "System can update referral tracking" ON public.lead_referral_tracking;
CREATE POLICY "System can update referral tracking"
  ON public.lead_referral_tracking
  FOR UPDATE
  USING (true); -- Will be controlled by service role in backend

-- Super Admins can view all referral tracking
DROP POLICY IF EXISTS "Super admins can view all referral tracking" ON public.lead_referral_tracking;
CREATE POLICY "Super admins can view all referral tracking"
  ON public.lead_referral_tracking
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid()
      AND role = 'SUPER_ADMIN'
    )
  );

-- ============================================================================
-- SHORT_LINKS RLS POLICIES
-- ============================================================================

-- Partners can view their own short links
DROP POLICY IF EXISTS "Partners can view own short links" ON public.short_links;
CREATE POLICY "Partners can view own short links"
  ON public.short_links
  FOR SELECT
  USING (
    created_by_user_id = auth.uid()
  );

-- Partners can create short links
DROP POLICY IF EXISTS "Partners can create short links" ON public.short_links;
CREATE POLICY "Partners can create short links"
  ON public.short_links
  FOR INSERT
  WITH CHECK (
    created_by_user_id = auth.uid()
  );

-- Public can access short links for redirection (handled by service role)
-- This will be managed in the backend API with service role client

-- ============================================================================
-- 7. HELPER FUNCTIONS
-- ============================================================================

-- Function to get lead statistics for a partner
CREATE OR REPLACE FUNCTION get_partner_lead_stats(p_partner_id UUID)
RETURNS TABLE (
  total_leads BIGINT,
  pending_leads BIGINT,
  opened_leads BIGINT,
  filled_leads BIGINT,
  submitted_leads BIGINT,
  converted_leads BIGINT,
  dropped_leads BIGINT,
  whatsapp_sent_count BIGINT,
  conversion_rate NUMERIC(5,2)
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT AS total_leads,
    COUNT(*) FILTER (WHERE form_status = 'PENDING')::BIGINT AS pending_leads,
    COUNT(*) FILTER (WHERE form_status = 'OPENED')::BIGINT AS opened_leads,
    COUNT(*) FILTER (WHERE form_status = 'FILLED')::BIGINT AS filled_leads,
    COUNT(*) FILTER (WHERE form_status = 'SUBMITTED')::BIGINT AS submitted_leads,
    COUNT(*) FILTER (WHERE lead_status = 'CONVERTED')::BIGINT AS converted_leads,
    COUNT(*) FILTER (WHERE lead_status = 'DROPPED')::BIGINT AS dropped_leads,
    SUM(whatsapp_sent_count)::BIGINT AS whatsapp_sent_count,
    CASE
      WHEN COUNT(*) > 0 THEN
        ROUND((COUNT(*) FILTER (WHERE converted = TRUE)::NUMERIC / COUNT(*)::NUMERIC) * 100, 2)
      ELSE
        0
    END AS conversion_rate
  FROM public.partner_leads
  WHERE partner_id = p_partner_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- 8. COMMENTS
-- ============================================================================

COMMENT ON TABLE public.partner_leads IS 'Stores leads generated by Business Partners and Business Associates via shared links';
COMMENT ON TABLE public.lead_referral_tracking IS 'Tracks the complete referral chain for regulatory compliance and audit';
COMMENT ON TABLE public.short_links IS 'Stores shortened URLs for easy sharing and tracking';

COMMENT ON COLUMN public.partner_leads.trace_token IS 'Encrypted referral token format: role_userID_partnerID_timestamp_random';
COMMENT ON COLUMN public.partner_leads.form_status IS 'PENDING: Not opened, OPENED: Link clicked, FILLED: Partially filled, SUBMITTED: Completed';
COMMENT ON COLUMN public.partner_leads.lead_status IS 'NEW, CONTACTED, QUALIFIED, CONVERTED, DROPPED';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
