/**
 * Loan Application Module - Constants & Configuration
 * Premium Design System Constants
 */

import type {
  LoanTypeConfig,
  LoanCategoryConfig,
  LoanTypeCode,
  LoanCategory,
  DocumentConfig,
  DocumentType,
} from './types';

// =====================================================
// LOAN CATEGORIES
// =====================================================

export const LOAN_CATEGORIES: LoanCategoryConfig[] = [
  {
    id: 'CONSUMER',
    name: 'Consumer Loans',
    description: 'Personal and retail lending for individuals',
    icon: 'Users',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-cyan-500',
    loanTypes: [
      'PERSONAL_LOAN',
      'HOME_LOAN',
      'NEW_CAR_LOAN',
      'USED_CAR_LOAN',
      'BUSINESS_LOAN',
      'EDUCATION_LOAN',
      'LAP',
      'GOLD_LOAN',
      'CREDIT_CARD',
    ],
  },
  {
    id: 'BUSINESS',
    name: 'Business & Working Capital',
    description: 'Fuel your business growth and operations',
    icon: 'Briefcase',
    color: '#8B5CF6',
    gradient: 'from-purple-500 to-indigo-500',
    loanTypes: [
      'WORKING_CAPITAL',
      'MACHINERY_LOAN',
      'BILL_DISCOUNTING',
      'OVERDRAFT',
      'CASH_CREDIT',
    ],
  },
  {
    id: 'PROPERTY',
    name: 'Property & Asset-Backed',
    description: 'Unlock the value of your assets',
    icon: 'Building2',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-orange-500',
    loanTypes: [
      'MORTGAGE_LOAN',
      'LOAN_AGAINST_SHARES',
      'LEASE_RENTAL_DISCOUNTING',
      'REFINANCE',
      'BALANCE_TRANSFER',
      'TOPUP_VEHICLE_LOAN',
    ],
  },
  {
    id: 'PROFESSIONAL',
    name: 'Professional Loans',
    description: 'Specialized loans for professionals & institutions',
    icon: 'Stethoscope',
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-500',
    loanTypes: [
      'LOAN_TO_DOCTORS',
      'LOAN_TO_HOSPITALS',
      'LOAN_TO_EDUCATIONAL_INSTITUTIONS',
      'LOAN_TO_BUILDERS',
      'LOAN_TO_PROFESSIONALS',
    ],
  },
  {
    id: 'NRI',
    name: 'NRI Loans',
    description: 'Special loans for Non-Resident Indians',
    icon: 'Globe',
    color: '#10B981',
    gradient: 'from-emerald-500 to-teal-500',
    loanTypes: ['NRI_LOAN'],
  },
];

// =====================================================
// LOAN TYPE CONFIGURATIONS
// =====================================================

export const LOAN_TYPES: Record<LoanTypeCode, LoanTypeConfig> = {
  // ==================== CONSUMER LOANS ====================
  PERSONAL_LOAN: {
    code: 'PERSONAL_LOAN',
    name: 'Personal Loan',
    shortName: 'Personal',
    category: 'CONSUMER',
    icon: 'Wallet',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-blue-600',
    description: 'Instant funds for all your personal needs',
    tagline: 'Your dreams, our support',
    features: ['Quick Disbursal in 24 hrs', 'No Collateral Required', 'Flexible Tenure', 'Minimal Documentation'],
    minAmount: 50000,
    maxAmount: 5000000,
    minTenure: 12,
    maxTenure: 84,
    interestRateRange: '10.49% - 24%',
    processingTime: '24-48 hours',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 1,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'ADDRESS_PROOF', 'PHOTO'],
  },

  HOME_LOAN: {
    code: 'HOME_LOAN',
    name: 'Home Loan',
    shortName: 'Home',
    category: 'CONSUMER',
    icon: 'Home',
    color: '#22C55E',
    gradient: 'from-emerald-500 to-green-600',
    description: 'Make your dream home a reality',
    tagline: 'Home is where your story begins',
    features: ['Lowest Interest Rates', 'Up to 30 Years Tenure', 'Tax Benefits u/s 80C & 24(b)', 'Balance Transfer Available'],
    minAmount: 500000,
    maxAmount: 100000000,
    minTenure: 60,
    maxTenure: 360,
    interestRateRange: '8.35% - 11%',
    processingTime: '7-14 days',
    requiresCollateral: true,
    requiresCoApplicant: true,
    popularityRank: 2,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'ITR', 'BANK_STATEMENT', 'PROPERTY_DOCS', 'ADDRESS_PROOF', 'PHOTO'],
  },

  NEW_CAR_LOAN: {
    code: 'NEW_CAR_LOAN',
    name: 'New Car Loan',
    shortName: 'New Car',
    category: 'CONSUMER',
    icon: 'Car',
    color: '#06B6D4',
    gradient: 'from-cyan-500 to-teal-600',
    description: 'Drive home your brand new car today',
    tagline: 'Your journey starts here',
    features: ['Up to 100% On-Road Funding', 'Quick Approval', 'Flexible EMI Options', 'Pre-approved Offers'],
    minAmount: 100000,
    maxAmount: 10000000,
    minTenure: 12,
    maxTenure: 84,
    interestRateRange: '7.25% - 14%',
    processingTime: '24-72 hours',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 3,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'ADDRESS_PROOF', 'PHOTO'],
  },

  USED_CAR_LOAN: {
    code: 'USED_CAR_LOAN',
    name: 'Used Car Loan',
    shortName: 'Used Car',
    category: 'CONSUMER',
    icon: 'CarFront',
    color: '#14B8A6',
    gradient: 'from-teal-500 to-emerald-600',
    description: 'Affordable financing for pre-owned vehicles',
    tagline: 'Quality rides, smart savings',
    features: ['Finance Up to 90% Value', 'Cars Up to 10 Years Old', 'Quick Valuation', 'Easy Documentation'],
    minAmount: 50000,
    maxAmount: 5000000,
    minTenure: 12,
    maxTenure: 60,
    interestRateRange: '9.5% - 18%',
    processingTime: '24-72 hours',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 7,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'VEHICLE_RC', 'ADDRESS_PROOF', 'PHOTO'],
  },

  BUSINESS_LOAN: {
    code: 'BUSINESS_LOAN',
    name: 'Business Loan',
    shortName: 'Business',
    category: 'CONSUMER',
    icon: 'Briefcase',
    color: '#8B5CF6',
    gradient: 'from-violet-500 to-purple-600',
    description: 'Fuel your business ambitions',
    tagline: 'Grow without limits',
    features: ['Collateral-Free Options', 'Quick Disbursal', 'Flexible Usage', 'Customized Repayment'],
    minAmount: 100000,
    maxAmount: 50000000,
    minTenure: 12,
    maxTenure: 60,
    interestRateRange: '11% - 24%',
    processingTime: '3-7 days',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 4,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'GST_CERTIFICATE', 'BUSINESS_PROOF', 'FINANCIAL_STATEMENTS'],
  },

  EDUCATION_LOAN: {
    code: 'EDUCATION_LOAN',
    name: 'Education Loan',
    shortName: 'Education',
    category: 'CONSUMER',
    icon: 'GraduationCap',
    color: '#6366F1',
    gradient: 'from-indigo-500 to-blue-600',
    description: 'Invest in your future with quality education',
    tagline: 'Education is the best investment',
    features: ['Study in India or Abroad', 'Moratorium Period', 'Tax Benefits u/s 80E', 'Covers All Expenses'],
    minAmount: 100000,
    maxAmount: 20000000,
    minTenure: 60,
    maxTenure: 180,
    interestRateRange: '8.5% - 15%',
    processingTime: '7-14 days',
    requiresCollateral: false,
    requiresCoApplicant: true,
    popularityRank: 6,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ADMISSION_LETTER', 'FEE_STRUCTURE', 'BANK_STATEMENT', 'ADDRESS_PROOF', 'PHOTO'],
  },

  LAP: {
    code: 'LAP',
    name: 'Loan Against Property',
    shortName: 'LAP',
    category: 'CONSUMER',
    icon: 'Building',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-orange-600',
    description: 'Unlock the value of your property',
    tagline: 'Your property, your power',
    features: ['Up to 75% of Property Value', 'Lower Interest Rates', 'Long Tenure', 'Multiple End Uses'],
    minAmount: 500000,
    maxAmount: 100000000,
    minTenure: 60,
    maxTenure: 180,
    interestRateRange: '9% - 14%',
    processingTime: '7-14 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 5,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'PROPERTY_DOCS', 'ADDRESS_PROOF', 'PHOTO'],
  },

  GOLD_LOAN: {
    code: 'GOLD_LOAN',
    name: 'Gold Loan',
    shortName: 'Gold',
    category: 'CONSUMER',
    icon: 'Gem',
    color: '#EAB308',
    gradient: 'from-yellow-500 to-amber-600',
    description: 'Instant cash against your gold ornaments',
    tagline: 'Turn gold into opportunities',
    features: ['Instant Disbursal', 'No Income Proof', 'Flexible Repayment', 'Safe Custody'],
    minAmount: 10000,
    maxAmount: 10000000,
    minTenure: 3,
    maxTenure: 36,
    interestRateRange: '7% - 15%',
    processingTime: '30 minutes',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 8,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ADDRESS_PROOF', 'PHOTO'],
  },

  CREDIT_CARD: {
    code: 'CREDIT_CARD',
    name: 'Credit Card',
    shortName: 'Credit Card',
    category: 'CONSUMER',
    icon: 'CreditCard',
    color: '#EF4444',
    gradient: 'from-red-500 to-rose-600',
    description: 'Premium credit cards with exclusive benefits',
    tagline: 'Spend smart, earn more',
    features: ['Reward Points', 'Cashback Offers', 'Travel Benefits', 'Zero Joining Fee'],
    minAmount: 25000,
    maxAmount: 1000000,
    minTenure: 0,
    maxTenure: 0,
    interestRateRange: '0% - 42%',
    processingTime: '3-7 days',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 9,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'SALARY_SLIP', 'BANK_STATEMENT', 'ADDRESS_PROOF', 'PHOTO'],
  },

  // ==================== BUSINESS & WORKING CAPITAL ====================
  WORKING_CAPITAL: {
    code: 'WORKING_CAPITAL',
    name: 'Working Capital Loan',
    shortName: 'Working Capital',
    category: 'BUSINESS',
    icon: 'RefreshCw',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-indigo-600',
    description: 'Manage your business cash flow seamlessly',
    tagline: 'Keep your business moving',
    features: ['Revolving Credit', 'Pay Interest Only on Usage', 'Quick Renewal', 'Flexible Limits'],
    minAmount: 500000,
    maxAmount: 100000000,
    minTenure: 12,
    maxTenure: 12,
    interestRateRange: '10% - 18%',
    processingTime: '5-10 days',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 10,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'GST_CERTIFICATE', 'FINANCIAL_STATEMENTS'],
  },

  MACHINERY_LOAN: {
    code: 'MACHINERY_LOAN',
    name: 'Machinery Loan',
    shortName: 'Machinery',
    category: 'BUSINESS',
    icon: 'Cog',
    color: '#64748B',
    gradient: 'from-slate-500 to-gray-600',
    description: 'Finance your equipment and machinery needs',
    tagline: 'Power your production',
    features: ['Up to 90% Financing', 'New & Used Machinery', 'Flexible Tenure', 'Quick Processing'],
    minAmount: 500000,
    maxAmount: 50000000,
    minTenure: 12,
    maxTenure: 84,
    interestRateRange: '10% - 16%',
    processingTime: '5-10 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 15,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'GST_CERTIFICATE', 'FINANCIAL_STATEMENTS', 'BUSINESS_PROOF'],
  },

  BILL_DISCOUNTING: {
    code: 'BILL_DISCOUNTING',
    name: 'Bill Discounting',
    shortName: 'Bill Discount',
    category: 'BUSINESS',
    icon: 'FileText',
    color: '#8B5CF6',
    gradient: 'from-purple-500 to-violet-600',
    description: 'Convert your invoices into instant cash',
    tagline: 'Cash flow, simplified',
    features: ['Instant Liquidity', 'No Collateral', 'Flexible Terms', 'Bulk Processing'],
    minAmount: 100000,
    maxAmount: 50000000,
    minTenure: 1,
    maxTenure: 6,
    interestRateRange: '12% - 20%',
    processingTime: '24-72 hours',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 18,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'BANK_STATEMENT', 'GST_CERTIFICATE', 'FINANCIAL_STATEMENTS'],
  },

  OVERDRAFT: {
    code: 'OVERDRAFT',
    name: 'Overdraft (OD)',
    shortName: 'OD',
    category: 'BUSINESS',
    icon: 'ArrowUpDown',
    color: '#06B6D4',
    gradient: 'from-cyan-500 to-blue-600',
    description: 'Flexible credit line for your business',
    tagline: 'Credit when you need it',
    features: ['Use as Needed', 'Interest on Utilized Amount', 'Easy Renewal', 'No End Use Restriction'],
    minAmount: 100000,
    maxAmount: 50000000,
    minTenure: 12,
    maxTenure: 12,
    interestRateRange: '10% - 16%',
    processingTime: '5-10 days',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 12,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'GST_CERTIFICATE', 'FINANCIAL_STATEMENTS'],
  },

  CASH_CREDIT: {
    code: 'CASH_CREDIT',
    name: 'Cash Credit (CC)',
    shortName: 'CC',
    category: 'BUSINESS',
    icon: 'Banknote',
    color: '#22C55E',
    gradient: 'from-green-500 to-emerald-600',
    description: 'Revolving credit facility against stock/receivables',
    tagline: 'Your stock, your credit',
    features: ['Against Stock/Receivables', 'Flexible Drawing', 'Lower Interest', 'Regular Assessment'],
    minAmount: 500000,
    maxAmount: 100000000,
    minTenure: 12,
    maxTenure: 12,
    interestRateRange: '9% - 15%',
    processingTime: '7-14 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 11,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'GST_CERTIFICATE', 'FINANCIAL_STATEMENTS'],
  },

  // ==================== PROPERTY & ASSET-BACKED ====================
  MORTGAGE_LOAN: {
    code: 'MORTGAGE_LOAN',
    name: 'Mortgage Loan',
    shortName: 'Mortgage',
    category: 'PROPERTY',
    icon: 'Building2',
    color: '#F59E0B',
    gradient: 'from-orange-500 to-amber-600',
    description: 'Secure financing against your property',
    tagline: 'Leverage your assets',
    features: ['High Loan Amount', 'Lower Rates', 'Long Tenure', 'Multiple End Uses'],
    minAmount: 1000000,
    maxAmount: 100000000,
    minTenure: 60,
    maxTenure: 180,
    interestRateRange: '9% - 13%',
    processingTime: '7-14 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 13,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'PROPERTY_DOCS', 'ADDRESS_PROOF'],
  },

  LOAN_AGAINST_SHARES: {
    code: 'LOAN_AGAINST_SHARES',
    name: 'Loan Against Shares',
    shortName: 'LAS',
    category: 'PROPERTY',
    icon: 'TrendingUp',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-cyan-600',
    description: 'Unlock liquidity from your investments',
    tagline: 'Invest & borrow smartly',
    features: ['Retain Ownership', 'Quick Processing', 'Continue Earning Dividends', 'Flexible Repayment'],
    minAmount: 100000,
    maxAmount: 50000000,
    minTenure: 12,
    maxTenure: 36,
    interestRateRange: '9% - 14%',
    processingTime: '24-72 hours',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 17,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'BANK_STATEMENT', 'ADDRESS_PROOF'],
  },

  LEASE_RENTAL_DISCOUNTING: {
    code: 'LEASE_RENTAL_DISCOUNTING',
    name: 'Lease Rental Discounting',
    shortName: 'LRD',
    category: 'PROPERTY',
    icon: 'Key',
    color: '#14B8A6',
    gradient: 'from-teal-500 to-cyan-600',
    description: 'Monetize your rental income stream',
    tagline: 'Rent today, cash now',
    features: ['Based on Rental Income', 'High LTV', 'Long Tenure', 'Prime Tenants Preferred'],
    minAmount: 5000000,
    maxAmount: 200000000,
    minTenure: 60,
    maxTenure: 180,
    interestRateRange: '8.5% - 12%',
    processingTime: '10-15 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 20,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'PROPERTY_DOCS'],
  },

  REFINANCE: {
    code: 'REFINANCE',
    name: 'Refinance',
    shortName: 'Refinance',
    category: 'PROPERTY',
    icon: 'RefreshCcw',
    color: '#22C55E',
    gradient: 'from-green-500 to-teal-600',
    description: 'Get better rates on your existing loan',
    tagline: 'Save on interest, live better',
    features: ['Lower Interest Rates', 'Reduced EMI', 'Top-up Available', 'Hassle-free Transfer'],
    minAmount: 500000,
    maxAmount: 100000000,
    minTenure: 60,
    maxTenure: 240,
    interestRateRange: '8% - 12%',
    processingTime: '7-14 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 14,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'BANK_STATEMENT', 'PROPERTY_DOCS'],
  },

  BALANCE_TRANSFER: {
    code: 'BALANCE_TRANSFER',
    name: 'Balance Transfer',
    shortName: 'BT',
    category: 'PROPERTY',
    icon: 'ArrowLeftRight',
    color: '#8B5CF6',
    gradient: 'from-purple-500 to-indigo-600',
    description: 'Transfer your loan for better terms',
    tagline: 'Switch & save',
    features: ['Better Interest Rates', 'Lower EMI', 'Top-up Option', 'Seamless Transfer'],
    minAmount: 500000,
    maxAmount: 100000000,
    minTenure: 60,
    maxTenure: 240,
    interestRateRange: '8% - 12%',
    processingTime: '7-14 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 16,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'BANK_STATEMENT', 'PROPERTY_DOCS'],
  },

  TOPUP_VEHICLE_LOAN: {
    code: 'TOPUP_VEHICLE_LOAN',
    name: 'Top-up Vehicle Loan',
    shortName: 'Top-up',
    category: 'PROPERTY',
    icon: 'CarFront',
    color: '#06B6D4',
    gradient: 'from-cyan-500 to-teal-600',
    description: 'Additional finance on your existing vehicle loan',
    tagline: 'More from your vehicle',
    features: ['Additional Funding', 'Existing Loan Continues', 'Quick Processing', 'Flexible Usage'],
    minAmount: 50000,
    maxAmount: 2000000,
    minTenure: 12,
    maxTenure: 48,
    interestRateRange: '11% - 18%',
    processingTime: '24-72 hours',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 19,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'BANK_STATEMENT', 'VEHICLE_RC'],
  },

  // ==================== PROFESSIONAL-SPECIFIC ====================
  LOAN_TO_DOCTORS: {
    code: 'LOAN_TO_DOCTORS',
    name: 'Loan to Doctors',
    shortName: 'Doctor Loan',
    category: 'PROFESSIONAL',
    icon: 'Stethoscope',
    color: '#EF4444',
    gradient: 'from-red-500 to-rose-600',
    description: 'Specialized loans for medical professionals',
    tagline: 'Helping healers grow',
    features: ['No Collateral up to 50L', 'Quick Approval', 'Equipment Financing', 'Clinic Setup'],
    minAmount: 500000,
    maxAmount: 50000000,
    minTenure: 12,
    maxTenure: 84,
    interestRateRange: '10% - 15%',
    processingTime: '3-7 days',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 21,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'PROFESSIONAL_CERT', 'ITR', 'BANK_STATEMENT'],
  },

  LOAN_TO_HOSPITALS: {
    code: 'LOAN_TO_HOSPITALS',
    name: 'Loan to Hospitals',
    shortName: 'Hospital Loan',
    category: 'PROFESSIONAL',
    icon: 'Hospital',
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-600',
    description: 'Infrastructure & equipment finance for hospitals',
    tagline: 'Building better healthcare',
    features: ['High Loan Amount', 'Equipment Finance', 'Construction Finance', 'Working Capital'],
    minAmount: 5000000,
    maxAmount: 500000000,
    minTenure: 60,
    maxTenure: 180,
    interestRateRange: '9% - 14%',
    processingTime: '15-30 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 24,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'PROFESSIONAL_CERT', 'ITR', 'BANK_STATEMENT', 'FINANCIAL_STATEMENTS', 'PROPERTY_DOCS'],
  },

  LOAN_TO_EDUCATIONAL_INSTITUTIONS: {
    code: 'LOAN_TO_EDUCATIONAL_INSTITUTIONS',
    name: 'Loan to Educational Institutions',
    shortName: 'Institution Loan',
    category: 'PROFESSIONAL',
    icon: 'School',
    color: '#3B82F6',
    gradient: 'from-blue-500 to-indigo-600',
    description: 'Finance for schools, colleges & coaching centers',
    tagline: 'Empowering education',
    features: ['Infrastructure Finance', 'Equipment Loans', 'Working Capital', 'Expansion Finance'],
    minAmount: 2000000,
    maxAmount: 200000000,
    minTenure: 60,
    maxTenure: 180,
    interestRateRange: '9% - 14%',
    processingTime: '15-30 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 25,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'FINANCIAL_STATEMENTS', 'PROPERTY_DOCS'],
  },

  LOAN_TO_BUILDERS: {
    code: 'LOAN_TO_BUILDERS',
    name: 'Loan to Builders',
    shortName: 'Builder Loan',
    category: 'PROFESSIONAL',
    icon: 'HardHat',
    color: '#F59E0B',
    gradient: 'from-amber-500 to-orange-600',
    description: 'Project finance for real estate developers',
    tagline: 'Building dreams together',
    features: ['Project Finance', 'Construction Finance', 'Land Purchase', 'Working Capital'],
    minAmount: 10000000,
    maxAmount: 1000000000,
    minTenure: 36,
    maxTenure: 84,
    interestRateRange: '12% - 18%',
    processingTime: '30-45 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 26,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'ITR', 'BANK_STATEMENT', 'FINANCIAL_STATEMENTS', 'PROPERTY_DOCS', 'BUSINESS_PROOF'],
  },

  LOAN_TO_PROFESSIONALS: {
    code: 'LOAN_TO_PROFESSIONALS',
    name: 'Loan to Professionals',
    shortName: 'Professional',
    category: 'PROFESSIONAL',
    icon: 'UserCheck',
    color: '#6366F1',
    gradient: 'from-indigo-500 to-purple-600',
    description: 'Loans for CAs, Lawyers, Architects & more',
    tagline: 'Fuel your practice',
    features: ['No Collateral up to 40L', 'Quick Processing', 'Office Setup', 'Equipment Finance'],
    minAmount: 500000,
    maxAmount: 30000000,
    minTenure: 12,
    maxTenure: 84,
    interestRateRange: '11% - 16%',
    processingTime: '3-7 days',
    requiresCollateral: false,
    requiresCoApplicant: false,
    popularityRank: 22,
    formSteps: [],
    requiredDocuments: ['PAN', 'AADHAAR', 'PROFESSIONAL_CERT', 'ITR', 'BANK_STATEMENT'],
  },

  // ==================== NRI LOANS ====================
  NRI_LOAN: {
    code: 'NRI_LOAN',
    name: 'NRI Loan',
    shortName: 'NRI',
    category: 'NRI',
    icon: 'Globe',
    color: '#10B981',
    gradient: 'from-emerald-500 to-teal-600',
    description: 'Home & property loans for Non-Resident Indians',
    tagline: 'Your roots, our commitment',
    features: ['Home Purchase in India', 'Property Investment', 'NRE/NRO Account Repayment', 'Power of Attorney Support'],
    minAmount: 1000000,
    maxAmount: 100000000,
    minTenure: 60,
    maxTenure: 240,
    interestRateRange: '8.5% - 12%',
    processingTime: '10-20 days',
    requiresCollateral: true,
    requiresCoApplicant: false,
    popularityRank: 23,
    formSteps: [],
    requiredDocuments: ['PAN', 'PASSPORT', 'BANK_STATEMENT', 'PROPERTY_DOCS', 'ADDRESS_PROOF'],
  },
};

// =====================================================
// DOCUMENT CONFIGURATIONS
// =====================================================

export const DOCUMENT_CONFIGS: Record<DocumentType, DocumentConfig> = {
  PAN: {
    type: 'PAN',
    name: 'PAN Card',
    description: 'Permanent Account Number card issued by Income Tax Department',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024, // 5MB
    isOptional: false,
    verificationRequired: true,
  },
  AADHAAR: {
    type: 'AADHAAR',
    name: 'Aadhaar Card',
    description: 'Unique Identification Number issued by UIDAI',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
  PASSPORT: {
    type: 'PASSPORT',
    name: 'Passport',
    description: 'Valid Indian passport',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: true,
    verificationRequired: false,
  },
  VOTER_ID: {
    type: 'VOTER_ID',
    name: 'Voter ID',
    description: 'Election Commission of India issued voter ID',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: true,
    verificationRequired: false,
  },
  DRIVING_LICENSE: {
    type: 'DRIVING_LICENSE',
    name: 'Driving License',
    description: 'Valid driving license issued by RTO',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: true,
    verificationRequired: false,
  },
  SALARY_SLIP: {
    type: 'SALARY_SLIP',
    name: 'Salary Slips',
    description: 'Last 3-6 months salary slips from employer',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 10 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  FORM_16: {
    type: 'FORM_16',
    name: 'Form 16',
    description: 'TDS certificate from employer for last 2 years',
    acceptedFormats: ['pdf'],
    maxSize: 10 * 1024 * 1024,
    isOptional: true,
    verificationRequired: false,
  },
  ITR: {
    type: 'ITR',
    name: 'Income Tax Returns',
    description: 'Last 2-3 years ITR with computation',
    acceptedFormats: ['pdf'],
    maxSize: 20 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
  BANK_STATEMENT: {
    type: 'BANK_STATEMENT',
    name: 'Bank Statements',
    description: 'Last 6-12 months bank statements',
    acceptedFormats: ['pdf'],
    maxSize: 20 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
  ADDRESS_PROOF: {
    type: 'ADDRESS_PROOF',
    name: 'Address Proof',
    description: 'Utility bill, rental agreement, or property documents',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 10 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  PHOTO: {
    type: 'PHOTO',
    name: 'Passport Size Photo',
    description: 'Recent passport size photograph',
    acceptedFormats: ['jpg', 'jpeg', 'png'],
    maxSize: 2 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  PROPERTY_DOCS: {
    type: 'PROPERTY_DOCS',
    name: 'Property Documents',
    description: 'Sale deed, title documents, approvals, tax receipts',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 50 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
  VEHICLE_RC: {
    type: 'VEHICLE_RC',
    name: 'Vehicle RC',
    description: 'Registration Certificate of the vehicle',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
  GST_CERTIFICATE: {
    type: 'GST_CERTIFICATE',
    name: 'GST Certificate',
    description: 'GST registration certificate',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
  BUSINESS_PROOF: {
    type: 'BUSINESS_PROOF',
    name: 'Business Proof',
    description: 'Udyam registration, shop act license, partnership deed',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 10 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  FINANCIAL_STATEMENTS: {
    type: 'FINANCIAL_STATEMENTS',
    name: 'Financial Statements',
    description: 'Audited balance sheet and P&L for last 3 years',
    acceptedFormats: ['pdf'],
    maxSize: 20 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  GOLD_RECEIPT: {
    type: 'GOLD_RECEIPT',
    name: 'Gold Receipt',
    description: 'Purchase receipt or hallmark certificate for gold',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: true,
    verificationRequired: false,
  },
  ADMISSION_LETTER: {
    type: 'ADMISSION_LETTER',
    name: 'Admission Letter',
    description: 'Offer letter or admission confirmation from institution',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  FEE_STRUCTURE: {
    type: 'FEE_STRUCTURE',
    name: 'Fee Structure',
    description: 'Detailed fee structure from the educational institution',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: false,
    verificationRequired: false,
  },
  PROFESSIONAL_CERT: {
    type: 'PROFESSIONAL_CERT',
    name: 'Professional Certificate',
    description: 'Registration certificate from professional body (MCI, ICAI, etc.)',
    acceptedFormats: ['pdf', 'jpg', 'jpeg', 'png'],
    maxSize: 5 * 1024 * 1024,
    isOptional: false,
    verificationRequired: true,
  },
};

// =====================================================
// HELPER FUNCTIONS
// =====================================================

export function getLoanTypeConfig(code: LoanTypeCode): LoanTypeConfig {
  return LOAN_TYPES[code];
}

export function getLoanCategory(categoryId: LoanCategory): LoanCategoryConfig | undefined {
  return LOAN_CATEGORIES.find(c => c.id === categoryId);
}

export function getLoanTypesByCategory(categoryId: LoanCategory): LoanTypeConfig[] {
  const category = getLoanCategory(categoryId);
  if (!category) return [];
  return category.loanTypes.map(code => LOAN_TYPES[code]);
}

export function getPopularLoanTypes(limit: number = 6): LoanTypeConfig[] {
  return Object.values(LOAN_TYPES)
    .sort((a, b) => a.popularityRank - b.popularityRank)
    .slice(0, limit);
}

export function formatCurrency(amount: number): string {
  if (amount >= 10000000) {
    return `₹${(amount / 10000000).toFixed(amount % 10000000 === 0 ? 0 : 2)} Cr`;
  } else if (amount >= 100000) {
    return `₹${(amount / 100000).toFixed(amount % 100000 === 0 ? 0 : 2)} L`;
  } else if (amount >= 1000) {
    return `₹${(amount / 1000).toFixed(0)}K`;
  }
  return `₹${amount}`;
}

export function formatAmountRange(min: number, max: number): string {
  return `${formatCurrency(min)} - ${formatCurrency(max)}`;
}
