import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import type { CurrentMonthPerformance, DSMMonthlyTargets, DSMDailyMetrics, MetricCard } from '@/lib/types/performance.types'
import { apiLogger } from '@/lib/utils/logger'


/**
 * GET /api/performance/dsm/current-month
 * Returns current month performance data for Direct Sales Manager
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient()

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 })
    }

    const { data: profile, error: profileError } = await supabase
      .from('users')
      .select('id, full_name, sub_role, location')
      .eq('id', user.id)
      .maybeSingle()

    if (profileError || !profile) {
      return NextResponse.json(
        { error: 'User profile not found. Please contact administrator.' },
        { status: 404 }
      )
    }

    if (profile.sub_role !== 'DIRECT_SALES_MANAGER') {
      return NextResponse.json(
        { error: 'Access denied. This endpoint is for Direct Sales Managers only.' },
        { status: 403 }
      )
    }

    const now = new Date()
    const currentMonth = now.getMonth() + 1
    const currentYear = now.getFullYear()

    const { data: targets } = await supabase
      .from('dsm_targets')
      .select('*')
      .eq('user_id', user.id)
      .eq('month', currentMonth)
      .eq('year', currentYear)
      .maybeSingle()

    const monthlyTargets: DSMMonthlyTargets = targets || {
      id: '',
      user_id: user.id,
      month: currentMonth,
      year: currentYear,
      team_revenue_target: 5000000,
      team_size_target: 15,
      team_leads_target: 300,
      team_conversion_rate_target: 25.0,
      individual_revenue_target: 1000000,
      team_training_sessions_target: 8,
      team_performance_score_target: 85.0,
      top_performers_count_target: 5,
      team_attrition_rate_target: 5.0,
      team_attendance_rate_target: 95.0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }

    const firstDayOfMonth = new Date(currentYear, currentMonth - 1, 1)
    const lastDayOfMonth = new Date(currentYear, currentMonth, 0)

    const { data: dailyMetrics } = await supabase
      .from('dsm_daily_metrics')
      .select('*')
      .eq('user_id', user.id)
      .gte('metric_date', firstDayOfMonth.toISOString().split('T')[0])
      .lte('metric_date', lastDayOfMonth.toISOString().split('T')[0])

    const currentMetrics = aggregateDSMMetrics(dailyMetrics || [])

    const metricCards: MetricCard[] = [
      {
        label: 'Team Revenue',
        value: currentMetrics.total_team_revenue,
        target: monthlyTargets.team_revenue_target,
        achievementPercentage: (currentMetrics.total_team_revenue / monthlyTargets.team_revenue_target) * 100,
        icon: '💰',
        color: 'emerald',
        category: 'revenue',
        description: 'Total team revenue generated',
        unit: '₹',
      },
      {
        label: 'Team Size',
        value: currentMetrics.current_team_size,
        target: monthlyTargets.team_size_target,
        achievementPercentage: (currentMetrics.current_team_size / monthlyTargets.team_size_target) * 100,
        icon: '👥',
        color: 'blue',
        category: 'team',
        description: 'Active team members',
      },
      {
        label: 'Team Leads Generated',
        value: currentMetrics.total_team_leads,
        target: monthlyTargets.team_leads_target,
        achievementPercentage: (currentMetrics.total_team_leads / monthlyTargets.team_leads_target) * 100,
        icon: '📊',
        color: 'indigo',
        category: 'lead',
        description: 'Leads generated by team',
      },
      {
        label: 'Team Conversion Rate',
        value: currentMetrics.team_conversion_rate,
        target: monthlyTargets.team_conversion_rate_target,
        achievementPercentage: (currentMetrics.team_conversion_rate / monthlyTargets.team_conversion_rate_target) * 100,
        icon: '🎯',
        color: 'purple',
        category: 'conversion',
        description: 'Team average conversion',
        unit: '%',
      },
      {
        label: 'Individual Revenue',
        value: currentMetrics.individual_revenue,
        target: monthlyTargets.individual_revenue_target,
        achievementPercentage: (currentMetrics.individual_revenue / monthlyTargets.individual_revenue_target) * 100,
        icon: '💵',
        color: 'green',
        category: 'revenue',
        description: 'Your personal revenue',
        unit: '₹',
      },
      {
        label: 'Training Sessions',
        value: currentMetrics.total_training_sessions,
        target: monthlyTargets.team_training_sessions_target,
        achievementPercentage: (currentMetrics.total_training_sessions / monthlyTargets.team_training_sessions_target) * 100,
        icon: '📚',
        color: 'cyan',
        category: 'activity',
        description: 'Team training conducted',
      },
      {
        label: 'Team Performance',
        value: currentMetrics.team_performance_score,
        target: monthlyTargets.team_performance_score_target,
        achievementPercentage: (currentMetrics.team_performance_score / monthlyTargets.team_performance_score_target) * 100,
        icon: '⭐',
        color: 'yellow',
        category: 'quality',
        description: 'Average team score',
        unit: '%',
      },
      {
        label: 'Top Performers',
        value: currentMetrics.top_performers_count,
        target: monthlyTargets.top_performers_count_target,
        achievementPercentage: (currentMetrics.top_performers_count / monthlyTargets.top_performers_count_target) * 100,
        icon: '🏆',
        color: 'amber',
        category: 'team',
        description: 'High achievers',
      },
      {
        label: 'Team Attrition Rate',
        value: currentMetrics.team_attrition_rate,
        target: monthlyTargets.team_attrition_rate_target,
        achievementPercentage: ((monthlyTargets.team_attrition_rate_target - currentMetrics.team_attrition_rate) / monthlyTargets.team_attrition_rate_target) * 100,
        icon: '📉',
        color: 'red',
        category: 'quality',
        description: 'Team retention (lower is better)',
        unit: '%',
        inverted: true,
      },
      {
        label: 'Team Attendance',
        value: currentMetrics.team_attendance_rate,
        target: monthlyTargets.team_attendance_rate_target,
        achievementPercentage: (currentMetrics.team_attendance_rate / monthlyTargets.team_attendance_rate_target) * 100,
        icon: '✅',
        color: 'teal',
        category: 'quality',
        description: 'Team attendance rate',
        unit: '%',
      },
    ]

    const overallScore = calculateDSMPerformanceScore(currentMetrics, monthlyTargets)

    const response: CurrentMonthPerformance<DSMMonthlyTargets, DSMDailyMetrics, any> = {
      userId: user.id,
      userName: profile.full_name,
      userRole: 'Direct Sales Manager',
      month: currentMonth,
      year: currentYear,
      summary: {
        overallScore,
        performanceGrade: getPerformanceGrade(overallScore),
        currentRank: 0,
        totalEmployees: 0,
        targetAchievement: calculateOverallAchievement(metricCards),
        trend: 'up',
      },
      metrics: metricCards,
      targets: monthlyTargets,
      currentMetrics,
      insights: [],
      graphData: {},
      leaderboard: [],
      currentUserRank: 0,
    }

    return NextResponse.json(response)
  } catch (error) {
    apiLogger.error('DSM current month error', error)
    return NextResponse.json(
      { error: 'Failed to fetch performance data' },
      { status: 500 }
    )
  }
}

function aggregateDSMMetrics(metrics: any[]): any {
  if (metrics.length === 0) {
    return {
      total_team_revenue: 0,
      current_team_size: 0,
      total_team_leads: 0,
      team_conversion_rate: 0,
      individual_revenue: 0,
      total_training_sessions: 0,
      team_performance_score: 0,
      top_performers_count: 0,
      team_attrition_rate: 0,
      team_attendance_rate: 0,
    }
  }

  const latestMetric = metrics[metrics.length - 1]

  return {
    total_team_revenue: metrics.reduce((sum, m) => sum + (m.team_revenue_generated || 0), 0),
    current_team_size: latestMetric.team_size || 0,
    total_team_leads: metrics.reduce((sum, m) => sum + (m.team_leads_generated || 0), 0),
    team_conversion_rate: calculateAverage(metrics, 'team_conversion_rate'),
    individual_revenue: metrics.reduce((sum, m) => sum + (m.individual_revenue_generated || 0), 0),
    total_training_sessions: metrics.reduce((sum, m) => sum + (m.training_sessions_conducted || 0), 0),
    team_performance_score: calculateAverage(metrics, 'team_performance_score'),
    top_performers_count: latestMetric.top_performers_count || 0,
    team_attrition_rate: latestMetric.team_attrition_rate || 0,
    team_attendance_rate: calculateAverage(metrics, 'team_attendance_rate'),
  }
}

function calculateDSMPerformanceScore(current: any, targets: DSMMonthlyTargets): number {
  const weights = {
    team_revenue: 0.30,
    team_size: 0.10,
    team_leads: 0.10,
    team_conversion: 0.10,
    individual_revenue: 0.15,
    training: 0.05,
    team_performance: 0.10,
    top_performers: 0.05,
    attrition: 0.025,
    attendance: 0.025,
  }

  let score = 0

  score += weights.team_revenue * Math.min(100, (current.total_team_revenue / targets.team_revenue_target) * 100)
  score += weights.team_size * Math.min(100, (current.current_team_size / targets.team_size_target) * 100)
  score += weights.team_leads * Math.min(100, (current.total_team_leads / targets.team_leads_target) * 100)
  score += weights.team_conversion * Math.min(100, (current.team_conversion_rate / targets.team_conversion_rate_target) * 100)
  score += weights.individual_revenue * Math.min(100, (current.individual_revenue / targets.individual_revenue_target) * 100)
  score += weights.training * Math.min(100, (current.total_training_sessions / targets.team_training_sessions_target) * 100)
  score += weights.team_performance * Math.min(100, (current.team_performance_score / targets.team_performance_score_target) * 100)
  score += weights.top_performers * Math.min(100, (current.top_performers_count / targets.top_performers_count_target) * 100)
  score += weights.attrition * Math.min(100, ((targets.team_attrition_rate_target - current.team_attrition_rate) / targets.team_attrition_rate_target) * 100)
  score += weights.attendance * Math.min(100, (current.team_attendance_rate / targets.team_attendance_rate_target) * 100)

  return Math.round(score)
}

function calculateAverage(metrics: any[], field: string): number {
  const validMetrics = metrics.filter(m => m[field] !== null && m[field] !== undefined)
  if (validMetrics.length === 0) return 0
  const sum = validMetrics.reduce((acc, m) => acc + (m[field] || 0), 0)
  return sum / validMetrics.length
}

function getPerformanceGrade(score: number): string {
  if (score >= 95) return 'A+'
  if (score >= 90) return 'A'
  if (score >= 85) return 'B+'
  if (score >= 80) return 'B'
  if (score >= 75) return 'C+'
  if (score >= 70) return 'C'
  if (score >= 60) return 'D'
  return 'F'
}

function calculateOverallAchievement(metrics: MetricCard[]): number {
  if (metrics.length === 0) return 0
  const total = metrics.reduce((sum, m) => sum + (m.achievementPercentage || 0), 0)
  return Math.round(total / metrics.length)
}
